# Configuration script to Travis-CI
language: python
python:
  - "2.7"
install:
  - pip install coverage --use-mirrors
  - pip install python-coveralls --use-mirrors
  - python setup.py install --always-unzip
script:
  - python bootstrap.py
  - ./bin/buildout
  - coverage run --source=src/soaringcoupons ./bin/test
# after_success:
#   coveralls
