# Configuration script to Travis-CI
language: python
python:
  - "2.7"
install:
  - python bootstrap.py
  - ./bin/buildout
  - pip install coverage --use-mirrors
  - pip install python-coveralls --use-mirrors
script:
  - coverage run --source=src/soaringcoupons ./bin/test
after_success:
  # coveralls
